backend:
  name: git-gateway
  branch: master
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
site_url: https://peacerivertrio.com
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    sort: 'date:desc'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: Summary, name: summary, widget: text, required: true }
      - { label: 'Publish Date', name: 'date', widget: 'date', required: true }
      - {
          label: 'Updated Date',
          name: 'update',
          widget: 'date',
          required: false,
        }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - {
          label: 'Author Link',
          name: 'authorlink',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
  - name: 'pages'
    label: 'CMS Pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: 'content/about.md'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Header Image
            name: img
            widget: image
            required: true
          - label: Page Content
            name: body
            widget: markdown
            required: true
      - label: 'Events'
        name: 'events'
        file: 'content/events.md'
        fields:
          - label: Title
            name: title
            widget: string
            required: true
          - label: Header Image
            name: img
            widget: image
            required: true
          - label: Events
            name: events
            widget: list
            required: true
            fields:
              - label: Name
                name: name
                widget: string
                required: true
              - label: Location
                name: Location
                widget: string
                required: true
              - label: Image
                name: image
                widget: image
                required: false
              - label: Date/Time
                name: date
                widget: datetime
                required: true
              - label: Description
                name: description
                widget: markdown
                required: true
